
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yefzzlfrirsfjzcsdcbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZnp6bGZyaXJzZmp6Y3NkY2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjgwMjEsImV4cCI6MjA1OTE0NDAyMX0.otVylBN978wz_OuV7DDiQZH5CaaShPceZ5h5_Inc1V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
